#!/bin/bash
#SBATCH -e /opt/slurm/output/slurm_%j.err
#SBATCH -o /opt/slurm/output/slurm_%j.out
#SBATCH -b now
source /usr/local/share/pipeline/bin/activate
python create_volume_from_contours.py --url $1 --volume $2
rsync -a /opt/slurm/ activebrainatlas:/opt/slurm
